spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/n11_gradution
    username: postgres
    password: Passwordw
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

server:
  error:
    include-message: always