spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/n11_gradution}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:Passwordw}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: ${DDL_AUTO:update}

server:
  error:
    include-message: always